export const JOB_ROLES = [
  { label: 'Administrative responsible',  groupKey: 'Administrative responsible' },
  { label: 'Budget Manager',              groupKey: 'Budget Manager' },
  { label: 'Cashflow Manager',            groupKey: 'Cashflow Manager' },
  { label: 'CEO',                         groupKey: 'CEO' },
  { label: 'CFO',                         groupKey: 'CFO' },
  { label: 'Community Manager',           groupKey: 'Community Manager' },
  { label: 'Customer referencer',         groupKey: 'Customer referencer' },
  { label: 'Directeur Marketing',         groupKey: 'Directeur Marketing' },
  { label: 'DRH',                         groupKey: 'DRH' },
  { label: 'Email Manager',               groupKey: 'Email Manager' },
  { label: 'HR',                          groupKey: 'HR' },
  { label: 'HR Reponsable',               groupKey: 'HR Reponsable' },
  { label: 'Infographiste',               groupKey: 'Infographiste' },
  { label: 'IT Person',                   groupKey: 'IT Person' },
  { label: 'LeadGen',                     groupKey: 'LeadGen' },
  { label: 'Legal',                       groupKey: 'Legal' },
  { label: 'Management Control',          groupKey: 'Management Control' },
  { label: 'Marketing Manager',           groupKey: 'Marketing Manager' },
  { label: 'Office Manager',              groupKey: 'Office Manager' },
  { label: 'Operation',                   groupKey: 'Operation' },
  { label: 'Operation On boarder',        groupKey: 'Operation On boarder' },
  { label: 'Recruiter',                   groupKey: 'Recruiter' },
  { label: 'Sales Development Represent', groupKey: 'Sales (Cold)' },
  { label: 'Sales (Hot)',                 groupKey: 'Sales (Hot)' },
  { label: 'Sales Cold Team Director',    groupKey: 'Sales Cold Team Director' },
  { label: 'Sales Cold Team Manager',     groupKey: 'Sales Cold Team Manager' },
  { label: 'Sales Manager',              groupKey: 'Sales Manager' },
  { label: 'Team Director',              groupKey: 'Team Director' },
  { label: 'Team Manager',               groupKey: 'Team Manager' },
  { label: 'Webmaster',                  groupKey: 'Webmaster' },
];
